### ISSUE TITLE
Power button lags on some device

### ISSUE THREAD

**Issue by aviraxp** [aviraxp/AdBlocker_Reborn#17]
**Description**

**Xposed log / logcat**

**Comment by aviraxp** [comment]
Possibly fixed by https://github.com/AdBlocker-Reborn/AdBlocker_Reborn/commit/0533580a3f934d1b3c317b5d38aec38a7500b6c8. Should be tested though.

**Comment by megabugman** [comment]
the lag issue is not fixed and 100% reproducible within Nougat 7.1.2 eg using Ressurection Remix or AOKP.

[04-05 10:42:24.225 407:407 I/Xposed]
Loading modules from /data/app/com.aviraxp.adblocker.continued-1/base.apk

[04-05 10:42:24.231 407:407 W/art]
Found duplicate classes, falling back to interpreter mode for /data/app/com.aviraxp.adblocker.continued-1/base.apk

[04-05 10:42:24.231 407:407 W/art]
Found duplicated class when checking oat files: 'Landroid/support/annotation/Keep;' in /data/app/eu.faircode.xlua-1/base.apk and /data/app/com.aviraxp.adblocker.continued-1/base.apk

[04-05 10:42:24.244 407:407 I/Xposed]
  Loading class com.aviraxp.adblocker.continued.hook.HookLoader

[04-05 10:42:24.354 407:407 W/art]
Found duplicated class when checking oat files: 'Landroid/support/annotation/AnimRes;' in /data/app/dev.ukanth.ufirewall.donate-2/base.apk and /data/app/com.aviraxp.adblocker.continued-1/base.apk

[04-05 10:42:30.277 861:861 W/PackageManager]
Not granting permission android.permission.READ_PHONE_STATE to package com.aviraxp.adblocker.continued because it was previously installed without

[04-05 10:42:30.975 410:410 W/cutils]
Expected path /data/data/com.aviraxp.adblocker.continued with mode 700 but found 755

[04-05 10:42:32.267 861:936 W/PackageManager]
Not granting permission android.permission.READ_PHONE_STATE to package com.aviraxp.adblocker.continued because it was previously installed without

[04-05 10:42:45.322 410:410 W/cutils]
Expected path /data/data/com.aviraxp.adblocker.continued with mode 700 but found 755

[04-05 10:51:54.963 23795:23884 W/System]
ClassLoader referenced unknown path: /data/app/com.aviraxp.adblocker.continued-1/lib/arm

[04-05 10:51:54.970 23795:23884 D/ApplicationLoaders]
ignored Vulkan layer search path /data/app/com.aviraxp.adblocker.continued-1/lib/arm for namespace 0x

**Comment by LFriede** [comment]
Sony Xperia Z3 Compact is also affected (rooted latest stock rom, 6.0.1), I'll try to do some debugging if I find some spare time.
